
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "IDENTIFIER LC_ALL NEIGH NUMBER READ SEND SETLOCALE STRINGstatement : expressionexpression : IDENTIFIER '(' arguments ')' expression : READ '(' STRING ')' expression : NEIGH '(' STRING ')' expression : SEND NUMBERarguments : argument\n                 | argument ',' argumentsargument : expression"
    
_lr_action_items = {'IDENTIFIER':([0,7,17,],[3,3,3,]),'READ':([0,7,17,],[4,4,4,]),'NEIGH':([0,7,17,],[5,5,5,]),'SEND':([0,7,17,],[6,6,6,]),'$end':([1,2,10,16,18,19,],[0,-1,-5,-2,-3,-4,]),'(':([3,4,5,],[7,8,9,]),'NUMBER':([6,],[10,]),'STRING':([8,9,],[14,15,]),',':([10,12,13,16,18,19,],[-5,17,-8,-2,-3,-4,]),')':([10,11,12,13,14,15,16,18,19,20,],[-5,16,-6,-8,18,19,-2,-3,-4,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,7,17,],[2,13,13,]),'arguments':([7,17,],[11,20,]),'argument':([7,17,],[12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expression','awdaw.py',44),
  ('expression -> IDENTIFIER ( arguments )','expression',4,'p_expression_function_call','awdaw.py',48),
  ('expression -> READ ( STRING )','expression',4,'p_expression_read','awdaw.py',52),
  ('expression -> NEIGH ( STRING )','expression',4,'p_expression_neigh','awdaw.py',56),
  ('expression -> SEND NUMBER','expression',2,'p_expression_send','awdaw.py',60),
  ('arguments -> argument','arguments',1,'p_arguments','awdaw.py',64),
  ('arguments -> argument , arguments','arguments',3,'p_arguments','awdaw.py',65),
  ('argument -> expression','argument',1,'p_argument','awdaw.py',72),
]
