wordlist = {
    "friend": "#include",
    "hurf": "void",
    "everypony": "public",
    "secret": "private",
    "libspace": "namespace",
    "send": "return",
    "int": "int",
    "float": "float",
    "string": "string",
    "char": "char",
    "bool": "bool",
    "true": "true",
    "false": "false",
    "if": "if",
    "else": "else",
    "while": "while",
    "for": "for",
    "break": "break",
    "continue": "continue",
    "new": "new",
    "delete": "delete",
    "null": "null",
    "this": "this",
    "class": "class",
}